# Four-page workbook generated by the reusable R application. Values and charts
# are a reproducible snapshot of the selected run, not an editable clinical model.

sbm_workbook_label <- function(x) {
  labels <- c(patient_id = "Patient", episode_id = "Stay", unit = "Ward / unit", band = "Time band",
    report_date = "Reporting day", hour = "Local hour", period = "Period", metric = "Measure",
    behaviour_type = "Behaviour type", behaviour = "Behaviour type", aggregation = "Weighting",
    n_observations = "Recorded checks", n_sleep_known = "Known sleep checks", n_asleep = "Asleep checks",
    n_awake = "Awake checks", sleep_pct = "Asleep (%)", sleep_known_pct = "Sleep field known (%)",
    n_behaviour_known_awake = "Awake behaviour known", n_behaviour_yes_awake = "Awake behaviour yes",
    behaviour_pct = "Behaviour while awake (%)", behaviour_known_awake_pct = "Awake behaviour field known (%)",
    n_admissions = "Stays", n_sleep_admissions = "Stays with sleep data", n_behaviour_admissions = "Stays with behaviour data",
    standardized_sleep_hours = "Standardized hours estimate", sleep_change_pp = "Sleep change (pp)",
    behaviour_change_pp = "Behaviour change (pp)", sleep_status = "Sleep comparison status",
    behaviour_status = "Behaviour comparison status", sleep_eligible = "Sleep comparison eligible",
    behaviour_eligible = "Behaviour comparison eligible", baseline_mean_pct = "Baseline mean daily (%)",
    report_mean_pct = "Report mean daily (%)", effect_pp = "Daily mean change (pp)",
    ci_low_pp = "Experimental CI lower (pp)", ci_high_pp = "Experimental CI upper (pp)",
    standard_error_pp = "Standard error (pp)", p_value = "Experimental unadjusted p", p_adjusted = "Experimental Holm p",
    n_baseline_days = "Baseline days", n_report_days = "Report days", eligible = "Eligible for test",
    significant = "Experimental adjusted-p flag", status = "Finding / eligibility", method = "Method", hac_lag = "HAC lag (days)",
    family_size = "Comparisons in family", source_row = "Source row", row = "Source row", code = "Issue code",
    message = "Issue explanation", value = "Value", numerator = "Yes / asleep checks", denominator = "Known eligible checks",
    pct = "Recorded proportion (%)", rate_pct = "Recorded proportion (%)", n_known = "Known eligible checks",
    n_yes = "Behaviour yes checks", known_pct = "Recorded field known (%)",
    baseline_pct = "Baseline (%)", report_pct = "Report (%)", change_pp = "Change (pp)",
    peer_pct = "Other ward patients (%)", peer_mean_pct = "Other patients mean (%)",
    patient_pct = "Patient (%)", difference_pp = "Patient minus peers (pp)", n_peer_patients = "Other patients",
    peer_patients = "Other patients", n_peer_episodes = "Other stays", n_peer_admissions = "Other eligible stays",
    peer_median_pct = "Other stays median (%)", peer_p25_pct = "Other stays 25th percentile (%)",
    peer_p75_pct = "Other stays 75th percentile (%)", percentile_midrank = "Peer percentile (0-100)",
    n_eligible = "Eligible checks", completeness_pct = "Recorded field known (%)", interpretation = "Interpretation",
    peer_numerator = "Other yes checks",
    peer_denominator = "Other known checks", peer_status = "Peer comparison status")
  vapply(x, function(nm) {
    if (nm %in% names(labels)) return(unname(labels[[nm]]))
    for (prefix in c("baseline_", "report_")) {
      if (startsWith(nm, prefix)) {
        rest <- substring(nm, nchar(prefix) + 1L)
        if (rest %in% names(labels)) return(paste(if (prefix == "baseline_") "Baseline" else "Report", tolower(labels[[rest]])))
      }
    }
    paste0(toupper(substr(gsub("_", " ", nm), 1L, 1L)), substring(gsub("_", " ", nm), 2L))
  }, character(1L), USE.NAMES = FALSE)
}

sbm_workbook_definition <- function(field, source = FALSE, config = NULL) {
  if (source) {
    mapped <- if (!is.null(config$columns)) names(config$columns)[unname(config$columns) == field] else character()
    detailed <- if (!is.null(config$behaviour_columns)) names(config$behaviour_columns)[unname(config$behaviour_columns) == field] else character()
    return(paste0("Original input field; supplied text is preserved, including leading zeroes. ",
      if (length(mapped)) paste0("Mapped to ", paste(mapped, collapse = ", "), ". ") else if (length(detailed))
        paste0("Explicit yes/no flag for ", paste(detailed, collapse = ", "), "; blank is unknown and its rate uses known awake checks. ") else "Not used by the core calculation unless mapped. ",
      "Leading spreadsheet formula characters are escaped for safe display; this does not alter analysis."))
  }
  known <- c(patient_id = "Stable patient identity; one person can have several stays.",
    episode_id = "Stable admission / episode identity. Baselines match this stay, patient and unit.",
    unit = "Unit recorded for the observation; summaries do not combine different units for a stay.",
    observation_id = "Unique source observation identifier; duplicates stop import.",
    observed_at = "Timestamp normalized to the configured time zone after validating its explicit source UTC offset.",
    report_date = "Local calendar date minus one day when the local clock is earlier than ReportingDayStart.",
    band = "Configured local-clock interval; start inclusive, end exclusive. Total spans all time bands.",
    hour = "Local clock hour, 0 to 23, independent of the reporting-day boundary.",
    sleep_state = "Normalized asleep, awake or unknown. Unmapped, conflicting and unresolved missing evidence remain unknown.",
    behaviour = "Normalized yes, no or unknown. Only explicitly awake checks enter the behaviour denominator.",
    source_row = "One-based input data row, excluding the source header; joins to row-level issues.",
    period = "Report or baseline based on inclusive reporting-date windows.",
    n_observations = "Number of received point observations, including unknown fields. Does not count missed scheduled checks.",
    n_sleep_known = "Number of checks explicitly classified awake or asleep.",
    n_asleep = "Checks classified asleep.", n_awake = "Checks classified awake.",
    sleep_pct = "100 x asleep checks / known sleep checks. Unavailable when the denominator is zero.",
    sleep_known_pct = "100 x known sleep checks / received checks; recorded-field completeness, not scheduled coverage.",
    n_behaviour_known_awake = "Checks classified awake with behaviour explicitly yes or no.",
    n_behaviour_yes_awake = "Checks classified awake with behaviour explicitly yes.",
    behaviour_pct = "100 x awake behaviour-yes checks / awake checks with known behaviour. Unknown is not absence.",
    behaviour_known_awake_pct = "100 x awake checks with known behaviour / all explicitly awake checks.",
    standardized_sleep_hours = "Sleep proportion scaled by nominal band hours. A standardized projection, not measured duration.",
    aggregation = "pooled_observations weights checks; equal_admission gives each eligible patient-stay/unit percentage equal weight.",
    n_admissions = "Number of patient-stay/unit groups in this unit summary.",
    n_sleep_admissions = "Number of stays with an available sleep percentage in the equal-admission mean.",
    n_behaviour_admissions = "Number of stays with an available awake behaviour percentage in the equal-admission mean.",
    sleep_change_pp = "Report pooled sleep percentage minus same-patient/stay/unit/band baseline percentage, subject to minimum data checks.",
    behaviour_change_pp = "Report pooled awake behaviour percentage minus matched baseline percentage, subject to minimum data checks.",
    baseline_mean_pct = "Arithmetic mean of available baseline daily percentages. Each eligible reporting day has equal weight.",
    report_mean_pct = "Arithmetic mean of available report daily percentages. Each eligible reporting day has equal weight.",
    effect_pp = "Report mean daily percentage minus baseline mean daily percentage, in percentage points. Differs from pooled-check change.",
    ci_low_pp = "Lower bound of the experimental pointwise (1 - Alpha) HAC confidence interval for daily mean change; not simultaneous across metrics and not clinically validated.",
    ci_high_pp = "Upper bound of the experimental pointwise (1 - Alpha) HAC confidence interval for daily mean change; not simultaneous across metrics and not clinically validated.",
    standard_error_pp = "Heteroskedasticity and autocorrelation consistent (HAC) standard error for the period-change coefficient.",
    p_value = "Two-sided unadjusted test p value for zero change in mean daily percentage under the documented model assumptions.",
    p_adjusted = "Holm-adjusted p value across the defined report comparison family. Read with effect size, confidence interval and eligibility.",
    n_baseline_days = "Baseline days with finite daily percentages before the eligibility decision.",
    n_report_days = "Report days with finite daily percentages before the eligibility decision.",
    eligible = "Whether the comparison meets the model's configured data and eligibility conditions.",
    significant = "Experimental adjusted-p flag when a comparison passes the report-wide Holm threshold; NA when untested. Test calibration is unresolved; not a validated finding of significance.",
    status = "Plain-language eligibility or exploratory statistical finding. An unavailable test is not a negative finding.",
    method = "Named statistical estimation procedure used for this comparison.",
    hac_lag = "Maximum daily lag included in the serial-correlation adjustment.",
    family_size = "Size of the report comparison family used in Holm multiple-testing adjustment.",
    metric = "Sleep, any behaviour while awake, or an individually configured behaviour measure.",
    behaviour_type = "Configured behaviour name. Separate types can co-occur and their percentages need not sum to 100%.",
    numerator = "Count of asleep/yes checks for this metric among the metric's known eligible observations.",
    denominator = "Known eligible observation count; behaviour requires explicitly awake checks and a known code for this type.",
    pct = "100 x metric numerator / metric denominator; zero denominator remains unavailable.",
    rate_pct = "100 x metric numerator / metric denominator; zero denominator remains unavailable.",
    n_yes = "Sleep metric: asleep checks. Behaviour metric: explicit yes checks for that field among awake observations.",
    n_known = "Sleep metric: awake plus asleep checks. Behaviour metric: awake observations with that field explicitly yes or no.",
    known_pct = "Recorded known-field percentage for this metric; not scheduled observation coverage.",
    patient_pct = "Focus patient proportion for the current period, with this metric's known eligible denominator.",
    peer_pct = "Descriptive pooled proportion for eligible other patients in the supplied ward data and report period, excluding the entire focus patient.",
    peer_mean_pct = "Descriptive arithmetic mean of eligible other-patient admission rates in the same ward and report period; each admission has equal weight.",
    peer_median_pct = "Median eligible other-patient admission rate in the same ward and report period.",
    peer_p25_pct = "25th percentile of eligible other-patient admission rates (R type 7 interpolation).",
    peer_p75_pct = "75th percentile of eligible other-patient admission rates (R type 7 interpolation).",
    percentile_midrank = "100 x (peer admission rates below the patient + half of equal peer rates) / eligible peer admissions. A descriptive rank, not a p value or risk score.",
    n_eligible = "Received checks eligible for this field: all observations for sleep; explicitly awake observations for each behaviour.",
    completeness_pct = "100 x n_known / n_eligible for this field. Completeness reflects received records, not missed scheduled checks.",
    n_peer_admissions = "Eligible peer admission/unit groups, with every admission of the focus person excluded.",
    difference_pp = "Patient minus other ward patients, in percentage points; descriptive and not adjusted for case mix.",
    n_peer_patients = "Distinct eligible other patients in supplied ward data contributing to the reference; excludes every stay of the focus person.",
    peer_status = "Whether a descriptive peer reference is available and any eligibility reason.",
    row = "Source data row associated with an import or normalization issue.",
    code = "Machine-readable quality issue code.", message = "Plain-language explanation of a row-level issue.")
  if (field %in% names(known)) return(unname(known[[field]]))
  for (prefix in c("baseline_", "report_")) {
    if (startsWith(field, prefix)) return(paste(if (prefix == "baseline_") "Baseline period:" else "Report period:",
      sbm_workbook_definition(substring(field, nchar(prefix) + 1L), FALSE, config)))
  }
  if (grepl("eligible$", field)) return("Whether the descriptive comparison meets configured count and recorded-completeness thresholds.")
  if (grepl("status$", field)) return("Comparison eligibility, missing-data or quality explanation. Unavailable does not mean no change.")
  if (grepl("^sbm_", field)) return(sbm_workbook_definition(sub("^sbm_", "", field), FALSE, config))
  if (grepl("_pct$", field)) return("Percentage metric in the named summary; Excel displays a fraction as 0.0%. Read its metric-specific known denominator.")
  if (grepl("_pp$", field)) return("Difference in percentage points; a numeric difference, not a percent relative change.")
  if (grepl("^n_|count|numerator|denominator", field)) return("Count for the named metric or reference population. Read alongside its matching percentage and selection.")
  "Derived or audit field supplied by this run; consult its named summary, configuration and row-level issues."
}

sbm_workbook_focus <- function(results, config) {
  targets <- unique(sbm_report_total(results$patient)[c("patient_id", "episode_id", "unit")])
  if (!nrow(targets)) stop("Dashboard requires a patient stay in the report period.", call. = FALSE)
  has_selection <- FALSE
  for (pair in list(c("dashboard_patient", "patient_id"), c("dashboard_episode", "episode_id"), c("dashboard_unit", "unit"))) {
    selected <- config[[pair[1L]]]
    if (!is.null(selected) && length(selected) && nzchar(selected[1L])) {
      has_selection <- TRUE
      targets <- targets[targets[[pair[2L]]] == selected[1L], , drop = FALSE]
    }
  }
  if (!nrow(targets)) stop("Dashboard selection does not match a patient, stay and unit in the report.", call. = FALSE)
  if (has_selection && nrow(targets) > 1L) stop("Dashboard selection matches multiple stays or units; specify DashboardPatient, DashboardEpisode and DashboardUnit until the focus is unique.", call. = FALSE)
  targets[1L, , drop = FALSE]
}

write_dashboard_workbook <- function(results, config, output_dir) {
  if (!requireNamespace("openxlsx", quietly = TRUE)) return(NULL)
  if (!dir.exists(output_dir)) dir.create(output_dir, recursive = TRUE)
  wb <- openxlsx::createWorkbook(creator = "Sleep & Behaviour Monitoring", title = "Sleep & Behaviour Monitoring")
  sheets <- c("Dashboard", "Expanded analytics", "Raw data", "Documentation")
  # Avoid combining worksheet tab colours with fit-to-page in older openxlsx:
  # those releases can emit a duplicated worksheet root element.
  for (sheet in sheets) openxlsx::addWorksheet(wb, sheet, gridLines = FALSE)
  openxlsx::modifyBaseFont(wb, fontSize = 10, fontColour = "#203B46", fontName = "Calibri")
  palette <- list(ink = "#163641", teal = "#087F83", pale = "#E9F3F2", light = "#F4F7F8", muted = "#526672", amber = "#A65B34")
  styles <- list(title = openxlsx::createStyle(fontSize = 21, textDecoration = "bold", fontColour = "#FFFFFF", fgFill = palette$ink, valign = "center"),
    subtitle = openxlsx::createStyle(fontSize = 10, fontColour = palette$muted, wrapText = TRUE, valign = "center"),
    section = openxlsx::createStyle(fontSize = 12, textDecoration = "bold", fontColour = palette$ink, fgFill = palette$pale, valign = "center"),
    header = openxlsx::createStyle(fontSize = 9, textDecoration = "bold", fontColour = "#FFFFFF", fgFill = palette$teal, wrapText = TRUE, valign = "center"),
    body = openxlsx::createStyle(fontSize = 10, valign = "center", wrapText = TRUE),
    tiny = openxlsx::createStyle(fontSize = 8, fontColour = palette$muted, wrapText = TRUE, valign = "center"),
    number = openxlsx::createStyle(numFmt = "0.0", valign = "center"),
    count = openxlsx::createStyle(numFmt = "#,##0", valign = "center"),
    percent = openxlsx::createStyle(numFmt = "0.0%", valign = "center"),
    pp = openxlsx::createStyle(numFmt = "0.0", valign = "center"),
    probability = openxlsx::createStyle(numFmt = "0.000", valign = "center"),
    date = openxlsx::createStyle(numFmt = "yyyy-mm-dd", valign = "center"),
    card_label = openxlsx::createStyle(fontSize = 9, textDecoration = "bold", fgFill = palette$pale, fontColour = palette$muted),
    card_value = openxlsx::createStyle(fontSize = 23, textDecoration = "bold", fgFill = palette$pale, fontColour = palette$teal),
    focus = openxlsx::createStyle(fontSize = 11, textDecoration = "bold", fgFill = palette$pale, wrapText = TRUE, valign = "center"))
  safe <- function(df) sbm_report_csv_safe(df)
  text <- function(sheet, row, value, cols = 1:12, style = styles$body, height = NULL) {
    if (length(cols) > 1L) openxlsx::mergeCells(wb, sheet, cols = cols, rows = row)
    val <- safe(data.frame(text = as.character(value), stringsAsFactors = FALSE))$text
    openxlsx::writeData(wb, sheet, val, startRow = row, startCol = min(cols), colNames = FALSE, keepNA = FALSE)
    openxlsx::addStyle(wb, sheet, style, rows = row, cols = cols, gridExpand = TRUE, stack = TRUE)
    if (!is.null(height)) openxlsx::setRowHeights(wb, sheet, row, height)
  }
  numeric_style <- function(field) {
    if (field %in% c("p_value", "p_adjusted")) return(styles$probability)
    if (grepl("_pct$|^pct$", field)) return(styles$percent)
    if (grepl("_pp$", field)) return(styles$pp)
    if (grepl("^n_|^row$|source_row|denominator|numerator|^hour$|family_size|hac_lag", field)) return(styles$count)
    styles$number
  }
  prepared <- function(df, percent = TRUE) {
    for (nm in names(df)) {
      if (inherits(df[[nm]], "POSIXt")) df[[nm]] <- format(df[[nm]], "%Y-%m-%d %H:%M:%S %z", tz = config$timezone)
      if (is.numeric(df[[nm]]) && !inherits(df[[nm]], "Date")) {
        df[[nm]][!is.finite(df[[nm]])] <- NA_real_
        if (percent && grepl("_pct$|^pct$", nm)) df[[nm]] <- df[[nm]] / 100
      }
    }
    safe(df)
  }
  table_index <- 0L
  table <- function(sheet, row, df, title, note = "", max_cols = 12L, raw = FALSE) {
    text(sheet, row, title, cols = seq_len(if (raw) max(12L, ncol(df)) else 12L), style = styles$section, height = 24)
    row <- row + 1L
    if (nzchar(note)) { text(sheet, row, note, cols = seq_len(if (raw) max(12L, ncol(df)) else 12L), style = styles$subtitle, height = 30); row <- row + 1L }
    if (!is.data.frame(df) || !nrow(df) || !ncol(df)) {
      text(sheet, row, "No rows available for this run.", style = styles$subtitle, height = 23)
      return(row + 3L)
    }
    # Wide source remains intact; derived tables split into vertical panels while
    # repeating their identity keys so no information is silently discarded.
    if (!raw && ncol(df) > max_cols) {
      keys <- intersect(c("patient_id", "episode_id", "unit", "band", "period", "metric", "behaviour_type", "report_date", "hour", "aggregation"), names(df))
      keys <- utils::head(keys, max_cols - 2L)
      rest <- setdiff(names(df), keys)
      groups <- split(rest, ceiling(seq_along(rest) / (max_cols - length(keys))))
      for (i in seq_along(groups)) row <- table(sheet, row, df[c(keys, groups[[i]])],
        paste0(title, " | detail ", i, " of ", length(groups)), max_cols = max_cols)
      return(row)
    }
    original <- names(df)
    rendered <- prepared(df, percent = !raw)
    if (!raw) names(rendered) <- make.unique(sbm_workbook_label(original), sep = " ")
    table_index <<- table_index + 1L
    openxlsx::writeDataTable(wb, sheet, rendered, startRow = row, tableName = paste0("MonitoringTable", table_index),
      tableStyle = "TableStyleMedium2", withFilter = TRUE, keepNA = FALSE)
    openxlsx::setRowHeights(wb, sheet, row, if (raw) 34 else 42)
    openxlsx::addStyle(wb, sheet, styles$header, rows = row, cols = seq_len(ncol(df)), gridExpand = TRUE, stack = TRUE)
    # Excel table styling already provides readable alternating rows. Avoid
    # materializing a style on every raw cell: large ward exports otherwise
    # become needlessly slow and huge. Small overview tables get wrapped rows.
    if (!raw && nrow(df) <= 300L) {
      text_cols <- vapply(df, is.character, logical(1L))
      heights <- rep(30, nrow(df))
      if (any(text_cols)) {
        lengths <- vapply(df[text_cols], function(x) ifelse(is.na(x), 0, nchar(x)), numeric(nrow(df)))
        if (is.null(dim(lengths))) lengths <- matrix(lengths, nrow = nrow(df), ncol = sum(text_cols))
        heights <- pmax(30, pmin(180, 12 * ceiling(apply(lengths, 1L, max) / 22)))
      }
      openxlsx::setRowHeights(wb, sheet, seq_len(nrow(df)) + row, heights)
      openxlsx::addStyle(wb, sheet, styles$body, rows = seq_len(nrow(df)) + row, cols = seq_len(ncol(df)), gridExpand = TRUE, stack = FALSE)
    }
    for (j in seq_along(df)) {
      if (!raw && inherits(df[[j]], "Date")) openxlsx::addStyle(wb, sheet, styles$date, rows = seq_len(nrow(df)) + row, cols = j, stack = FALSE)
      else if (!raw && is.numeric(df[[j]]) && grepl("_pct$|^pct$|_pp$|^p_value$|^p_adjusted$", original[j]))
        openxlsx::addStyle(wb, sheet, numeric_style(original[j]), rows = seq_len(nrow(df)) + row, cols = j, stack = FALSE)
    }
    row + nrow(df) + 3L
  }
  date_range <- function(start, end) {
    if (!length(start) || !length(end) || is.na(start) || is.na(end)) "Not selected"
    else paste(format(as.Date(start), "%d %b %Y"), "to", format(as.Date(end), "%d %b %Y"))
  }
  period <- date_range(config$start_date, config$end_date)
  baseline <- date_range(config$baseline_start, config$baseline_end)
  badge <- if (isTRUE(config$synthetic)) "SYNTHETIC DEMONSTRATION" else "LOCAL OBSERVATION REPORT"
  focus <- sbm_workbook_focus(results, config)
  focus_rows <- sbm_report_subset(results$patient, focus)
  total <- sbm_report_total(focus_rows)
  focus_label <- paste0("Patient: ", focus$patient_id, "   |   Stay: ", focus$episode_id, "   |   Ward: ", focus$unit)
  chart_dir <- tempfile("monitoring-workbook-")
  dir.create(chart_dir)
  on.exit(unlink(chart_dir, recursive = TRUE), add = TRUE)

  # 1. Patient-focused printable front page.
  sheet <- "Dashboard"
  openxlsx::setColWidths(wb, sheet, 1:12, 8)
  text(sheet, 1, config$title, style = styles$title, height = 31)
  text(sheet, 2, paste(badge, "| Report:", period, "(inclusive)"), style = styles$subtitle, height = 22)
  text(sheet, 3, paste0("Baseline: ", baseline, " (inclusive)   |   ", config$timezone, "   |   Reporting day starts ", sbm_report_clock(config$reporting_day_start)), style = styles$subtitle, height = 23)
  text(sheet, 4, focus_label, style = styles$focus, height = 30)
  cards <- list(c("Recorded checks", "n_observations"), c("Asleep checks", "sleep_pct"),
    c("Behaviour while awake", "behaviour_pct"), c("Sleep field known", "sleep_known_pct"))
  for (i in seq_along(cards)) {
    cols <- ((i - 1L) * 3L + 1L):(i * 3L)
    text(sheet, 6L, cards[[i]][1L], cols, styles$card_label, 18)
    value <- sbm_report_value(total, cards[[i]][2L])
    openxlsx::mergeCells(wb, sheet, cols = cols, rows = 7L)
    if (is.finite(value)) openxlsx::writeData(wb, sheet, if (i == 1L) value else value / 100, startRow = 7L, startCol = min(cols), colNames = FALSE)
    else text(sheet, 7L, "Unavailable", min(cols), styles$card_value)
    openxlsx::addStyle(wb, sheet, styles$card_value, rows = 7L, cols = cols, gridExpand = TRUE, stack = TRUE)
    openxlsx::addStyle(wb, sheet, if (i == 1L) styles$count else styles$percent, rows = 7L, cols = min(cols), stack = TRUE)
  }
  openxlsx::setRowHeights(wb, sheet, 7L, 32)
  text(sheet, 8, "Percentages describe recorded checks; unknown fields are excluded from the relevant known denominator.", style = styles$tiny, height = 19)
  text(sheet, 10, "Time-band summary", style = styles$section, height = 22)
  columns <- list(1:2, 3L, 4L, 5L, 6L, 7L, 8:9, 10:12)
  fields <- c("band", "n_observations", "sleep_pct", "n_sleep_known", "behaviour_pct", "n_behaviour_known_awake", "sleep_known_pct", "behaviour_known_awake_pct")
  headers <- c("Time band", "Checks", "Asleep %", "Known sleep", "Behaviour %", "Known awake behaviour", "Sleep field known %", "Awake behaviour field known %")
  for (i in seq_along(fields)) text(sheet, 11L, headers[i], columns[[i]], styles$header, 37)
  focus_rows <- focus_rows[order(match(focus_rows$band, c(config$bands$name, "Total"))), , drop = FALSE]
  for (i in seq_len(nrow(focus_rows))) {
    row <- 11L + i
    for (j in seq_along(fields)) {
      val <- focus_rows[[fields[j]]][i]
      cols <- columns[[j]]
      if (length(cols) > 1L) openxlsx::mergeCells(wb, sheet, cols = cols, rows = row)
      if (is.numeric(val) && grepl("_pct$", fields[j])) val <- val / 100
      openxlsx::writeData(wb, sheet, if (is.character(val)) safe(data.frame(v = val))$v else val,
        startRow = row, startCol = min(cols), colNames = FALSE, keepNA = FALSE)
      openxlsx::addStyle(wb, sheet, styles$body, rows = row, cols = cols, gridExpand = TRUE, stack = TRUE)
      if (is.numeric(val)) openxlsx::addStyle(wb, sheet, numeric_style(fields[j]), rows = row, cols = min(cols), stack = TRUE)
    }
    openxlsx::setRowHeights(wb, sheet, row, 23)
  }
  row <- 13L + nrow(focus_rows)
  text(sheet, row, "Sleep and behaviour over time", style = styles$section, height = 22)
  chart_path <- file.path(chart_dir, "dashboard-trend.png")
  sbm_report_png(sbm_report_chart_data(sbm_report_subset(results$daily, focus), "report_date", config),
    "report_date", "Patient daily pattern", chart_path)
  openxlsx::setRowHeights(wb, sheet, (row + 1L):(row + 15L), 14)
  openxlsx::insertImage(wb, sheet, chart_path, startRow = row + 1L, startCol = 1L, width = 7.35, height = 3.08, units = "in")
  row <- row + 17L
  text(sheet, row, "Lines share a 0-100% scale but have different denominators. Gaps are unavailable data. Charts are fixed snapshots; rerun to change the focus.", style = styles$tiny, height = 26)
  row <- row + 2L
  text(sheet, row, "Evidence of change from this person's baseline", style = styles$section, height = 23)
  row <- row + 1L
  stats <- if (is.data.frame(results$statistics)) sbm_report_subset(results$statistics, focus) else data.frame()
  if ("band" %in% names(stats)) stats <- sbm_report_total(stats)
  if (nrow(stats)) {
    primary <- which(tolower(stats$metric) %in% c("sleep", "any recorded behaviour"))
    other <- setdiff(seq_len(nrow(stats)), primary)
    if (length(other) && "effect_pp" %in% names(stats)) other <- other[order(-abs(stats$effect_pp[other]), na.last = TRUE)]
    shown <- stats[utils::head(c(primary, other), 5L), , drop = FALSE]
    if (isTRUE(config$statistics_enabled)) {
      stat_fields <- c("metric", "effect_pp", "ci_low_pp", "ci_high_pp", "p_adjusted", "n_baseline_days", "n_report_days", "status")
      stat_cols <- list(1:3, 4L, 5L, 6L, 7L, 8L, 9L, 10:12)
      stat_headers <- c("Measure", "Change pp", "Exp. CI low", "Exp. CI high", "Exp. Holm p", "Base days", "Report days", "Finding")
    } else {
      stat_fields <- c("metric", "baseline_mean_pct", "report_mean_pct", "effect_pp", "n_baseline_days", "n_report_days", "status")
      stat_cols <- list(1:3, 4L, 5L, 6L, 7L, 8L, 9:12)
      stat_headers <- c("Measure", "Baseline daily %", "Report daily %", "Change pp", "Base days", "Report days", "Finding")
    }
    for (j in seq_along(stat_fields)) text(sheet, row, stat_headers[j], stat_cols[[j]], styles$header, 32)
    for (i in seq_len(nrow(shown))) {
      for (j in seq_along(stat_fields)) {
        field <- stat_fields[j]; val <- if (field %in% names(shown)) shown[[field]][i] else NA
        cols <- stat_cols[[j]]
        if (length(cols) > 1L) openxlsx::mergeCells(wb, sheet, cols = cols, rows = row + i)
        if (field == "metric") val <- sbm_workbook_label(as.character(val))
        if (field == "status" && !is.na(val) && grepl("experimental inference disabled", val, fixed = TRUE)) val <- "Not tested: tests disabled"
        if (is.numeric(val) && grepl("_pct$", field)) val <- val / 100
        openxlsx::writeData(wb, sheet, if (is.character(val)) safe(data.frame(v = val))$v else val,
          startRow = row + i, startCol = min(cols), colNames = FALSE, keepNA = FALSE)
        openxlsx::addStyle(wb, sheet, if (field == "status") styles$tiny else styles$body, rows = row + i, cols = cols, gridExpand = TRUE, stack = TRUE)
        if (is.numeric(val)) openxlsx::addStyle(wb, sheet, numeric_style(field), rows = row + i, cols = min(cols), stack = TRUE)
      }
      openxlsx::setRowHeights(wb, sheet, row + i, 29)
    }
    row <- row + nrow(shown) + 1L
    if (nrow(stats) > nrow(shown)) { text(sheet, row, paste(nrow(shown), "of", nrow(stats), "measures shown; all comparisons are on Expanded analytics."), style = styles$tiny, height = 17); row <- row + 1L }
  } else { text(sheet, row, "Statistical comparisons are unavailable for this run. Descriptive values remain on Expanded analytics.", style = styles$subtitle, height = 30); row <- row + 1L }
  text(sheet, row, if (!isTRUE(config$statistics_enabled))
    "Changes use mean daily percentages. Significance testing is disabled by default pending method validation; blank CI and p values mean not tested. Descriptive change does not establish clinical importance or cause."
    else paste0("EXPERIMENTAL TESTS: changes use daily means; CI is pointwise ", 100 * (1 - if (is.null(config$alpha)) 0.05 else config$alpha), "%; p uses Holm correction. Calibration is not established for clinical use. A flag does not establish clinical importance or cause."),
    style = styles$tiny, height = 32)
  openxlsx::freezePane(wb, sheet, firstActiveRow = 5L)
  openxlsx::pageSetup(wb, sheet, orientation = "portrait", paperSize = 9L, fitToWidth = 1L, fitToHeight = 1L, left = 0.25, right = 0.25, top = 0.25, bottom = 0.25)

  # 2. Expanded analytics, with an auditable table for every derived result.
  sheet <- "Expanded analytics"
  openxlsx::setColWidths(wb, sheet, 1:12, 17)
  text(sheet, 1, "Expanded analytics", style = styles$title, height = 32)
  text(sheet, 2, paste(badge, "|", period, "| Baseline:", baseline), style = styles$subtitle, height = 26)
  text(sheet, 3, "Filter each table to isolate a person, stay, ward, behaviour or time band. Peer comparisons use eligible other patients in the supplied ward data, exclude the same person and are not adjusted for case mix.", style = styles$subtitle, height = 32)
  row <- 5L
  focus_stats <- if (is.data.frame(results$statistics)) sbm_report_subset(results$statistics, focus) else data.frame()
  focus_peers <- if (is.data.frame(results$peer_comparisons)) sbm_report_subset(results$peer_comparisons, focus) else data.frame()
  overview_fields <- c("metric", "baseline_mean_pct", "report_mean_pct", "effect_pp", "status")
  focus_overview <- if (nrow(focus_stats)) focus_stats[intersect(overview_fields, names(focus_stats))] else data.frame()
  if (nrow(focus_peers)) {
    peers_view <- focus_peers[intersect(c("metric", "report_rate_pct", "peer_mean_pct", "difference_pp", "n_peer_patients"), names(focus_peers))]
    focus_overview <- if (nrow(focus_overview)) merge(focus_overview, peers_view, by = "metric", all = TRUE, sort = FALSE) else peers_view
  }
  if ("status" %in% names(focus_overview)) {
    disabled <- !is.na(focus_overview$status) & grepl("experimental inference disabled", focus_overview$status, fixed = TRUE)
    focus_overview$status[disabled] <- "Not tested: tests disabled"
  }
  row <- table(sheet, row, focus_overview, "Focus patient | each behaviour and comparison", paste0(focus_label,
    ". Daily means compare own history; report rate and peer difference compare pooled current checks with equal-weight eligible peer stays."))
  text(sheet, row, "Focus patient: behaviour-specific ward comparison", style = styles$section, height = 24)
  text(sheet, row + 1L, "Report rate and equal-weight eligible peer-stay mean; descriptive context only. Fixed chart: Excel table filters do not redraw it.", style = styles$subtitle, height = 28)
  chart_path <- file.path(chart_dir, "expanded-behaviours.png")
  plot_peers <- focus_peers
  if (nrow(plot_peers)) plot_peers <- plot_peers[tolower(plot_peers$metric) != "sleep", , drop = FALSE]
  grDevices::png(chart_path, width = 1250L, height = 600L, res = 145L, bg = "#FFFEFA")
  if (nrow(plot_peers) && all(c("report_rate_pct", "peer_mean_pct") %in% names(plot_peers))) {
    graphics::par(mar = c(4.2, 13, 3, 1), family = "sans", col.axis = palette$muted)
    values <- rbind(plot_peers$report_rate_pct, plot_peers$peer_mean_pct)
    values[!is.finite(values)] <- NA_real_
    graphics::barplot(values[, ncol(values):1L, drop = FALSE], horiz = TRUE, beside = TRUE,
      names.arg = rev(plot_peers$metric), las = 1L, xlim = c(0, 100), col = c(palette$teal, palette$amber), border = NA,
      xlab = "Percentage of known awake checks", cex.names = 0.8)
    graphics::legend("topright", c("Patient current period", "Other eligible stays: mean"),
      fill = c(palette$teal, palette$amber), bty = "n", cex = 0.8)
  } else {
    graphics::plot.new(); graphics::text(0.5, 0.5, "No detailed ward comparison available in this run.", col = palette$muted)
  }
  grDevices::dev.off()
  openxlsx::insertImage(wb, sheet, chart_path, startRow = row + 3L, startCol = 1L, width = 9, height = 4.32, units = "in")
  openxlsx::setRowHeights(wb, sheet, (row + 3L):(row + 24L), 15)
  row <- row + 27L
  section_specs <- list(
    list("behaviour", "Individual behaviours", "Separate behaviour types retain their own known-awake denominators; types can co-occur."),
    list("statistics", "Statistical comparisons with own baseline", if (!isTRUE(config$statistics_enabled)) "Equal-weight daily means and descriptive change. Significance testing is disabled by default pending method validation; CI and p values remain blank."
      else "EXPERIMENTAL: equal-weight daily means, HAC intervals and Holm-adjusted tests. Test calibration is not established for clinical use; read Documentation and docs/STATISTICS.md."),
    list("peer_comparisons", "Comparison with other ward patients", "Eligible other patients in supplied ward data; all stays of the focus person are excluded. Selecting a dashboard patient does not restrict the ward reference. Each eligible peer stay has equal weight."),
    list("baseline", "Pooled-check comparison with own baseline", "Same patient, stay, ward and time band. Pooled checks weight observation-rich days more heavily than the statistical daily means."),
    list("patient", "Patient and stay time-band summary", "All selected report-period patient, stay and unit combinations."),
    list("unit", "Ward / unit summaries", "Pooled results weight observations. Equal-admission results weight eligible stays equally."))
  for (spec in section_specs) row <- table(sheet, row, results[[spec[[1L]]]], spec[[2L]], spec[[3L]])
  text(sheet, row, "Focus patient: time-of-day pattern", style = styles$section, height = 24)
  text(sheet, row + 1L, paste(focus_label, "| Fixed snapshot; filtering tables does not redraw this chart."), style = styles$subtitle, height = 30)
  chart_path <- file.path(chart_dir, "expanded-hourly.png")
  sbm_report_png(sbm_report_chart_data(sbm_report_subset(results$hourly, focus), "hour", config), "hour", "Patient time-of-day pattern", chart_path)
  openxlsx::insertImage(wb, sheet, chart_path, startRow = row + 3L, startCol = 1L, width = 9, height = 4.12, units = "in")
  openxlsx::setRowHeights(wb, sheet, (row + 3L):(row + 23L), 15)
  row <- row + 26L
  for (spec in list(list("behaviour_daily", "Individual behaviour by day"), list("metric_daily", "Daily metric inputs to statistical comparisons"),
                    list("daily", "Daily sleep and any-behaviour patterns"), list("hourly", "Clock-hour sleep and any-behaviour patterns")))
    row <- table(sheet, row, results[[spec[[1L]]]], spec[[2L]])
  openxlsx::freezePane(wb, sheet, firstActiveRow = 5L, firstActiveCol = 4L)
  openxlsx::pageSetup(wb, sheet, orientation = "landscape", paperSize = 9L, fitToWidth = 1L, fitToHeight = 0L)

  # 3. The actual selected source rows, never a substitute summary table.
  sheet <- "Raw data"
  raw <- if (is.data.frame(results$raw_data)) results$raw_data else data.frame()
  raw_prefix <- attr(raw, "derived_prefix")
  if (is.null(raw_prefix) || !length(raw_prefix)) raw_prefix <- "analysis_"
  openxlsx::setColWidths(wb, sheet, seq_len(max(12L, ncol(raw))), 22)
  text(sheet, 1, "Raw data | search and filter", cols = seq_len(max(12L, ncol(raw))), style = styles$title, height = 32)
  text(sheet, 2, paste(badge, "| Includes selected report and baseline source rows, with normalized and audit fields."), cols = seq_len(max(12L, ncol(raw))), style = styles$subtitle, height = 26)
  text(sheet, 3, "Use a header dropdown to filter or search values; use Ctrl+F to find text in this sheet. Source columns retain their original names; added audit fields are explained on Documentation. Filtering here does not change report values or charts.", cols = seq_len(max(12L, ncol(raw))), style = styles$subtitle, height = 30)
  raw_end <- table(sheet, 5L, raw, "Selected source observations", raw = TRUE)
  openxlsx::freezePane(wb, sheet, firstActiveRow = 7L, firstActiveCol = 4L)
  openxlsx::pageSetup(wb, sheet, orientation = "landscape", paperSize = 9L, fitToWidth = 1L, fitToHeight = 0L)

  # 4. Methods, exact field dictionary, settings and issue provenance.
  sheet <- "Documentation"
  openxlsx::setColWidths(wb, sheet, 1:12, 16)
  text(sheet, 1, "Documentation and data dictionary", style = styles$title, height = 32)
  text(sheet, 2, paste(badge, "| Software version", if (is.null(config$version)) "unspecified" else config$version), style = styles$subtitle, height = 24)
  definitions <- sbm_report_definitions(config)
  # Replace legacy statements about descriptive-only output with this run's actual statistical contract.
  keep <- !grepl("Statistical significance testing.*not|significance.*not implemented", definitions$definition, ignore.case = TRUE)
  definitions <- definitions[keep, , drop = FALSE]
  extra <- data.frame(term = c("Workbook navigation", "Static report", "Statistical question", "Statistical assumptions", "Multiple comparisons", "Clinical interpretation", "Peer comparison", "Provenance", "Raw-data handling", "Percentage units", "Unavailable values"),
    definition = c("Dashboard is a configured patient/stay/unit snapshot. Expanded analytics contains all selected comparisons. Raw data contains selected source rows. Documentation explains fields, settings and quality.",
      "All values and embedded plots are regenerated by the R tool for each run. Excel table filtering does not recalculate summaries or redraw the plots. Change configuration and rerun for a different focus or period.",
      "Compare equal-weight daily metric percentages in the report period with this patient's matching earlier baseline. The estimated change is in percentage points; this differs from a pooled-check proportion when daily denominators vary.",
      "Significance testing is disabled by default because initial calibration checks did not establish acceptable false-positive control. Optional experimental daily period-change regression uses a HAC variance estimate, but data thresholds do not validate its assumptions. Observation schedules, coding changes, treatment changes and case mix can confound results. See docs/STATISTICS.md in the source repository.",
      "Holm-adjusted p values control the defined report family only when the underlying tests are valid; that calibration remains unresolved here. A pointwise (1 - Alpha) confidence interval is not adjusted across metrics and may exclude zero while the Holm test does not pass. Blank p values mean untested, not no difference.",
      "An optional experimental adjusted-p flag is not a validated finding of statistical significance. It does not establish clinical importance, a behavioural cause, a medication effect, over-sedation or a staffing requirement. No diagnosis or treatment recommendation is generated.",
      "Eligible other patients in the supplied ward data and period provide descriptive context only. Every stay of the focus person is excluded, and each eligible peer stay has equal weight. Patient selection does not restrict the ward reference. Acuity, diagnosis, admission stage, recording practice and observation frequency can differ; no patient-vs-ward significance claim is made.",
      if (isTRUE(config$synthetic)) "Demonstration records are generated from versioned deterministic rules. No real patient record, source dataset or learned patient distribution is used; apparent patterns and p values demonstrate software only." else "Source observations were supplied locally. This report does not verify clinical provenance or validate the source measurement process. See the run receipt for source/configuration fingerprints.",
      "Only source rows inside the selected patient/unit and report/baseline scope appear. Normalized and audit fields are appended. Original text is retained, except a protective apostrophe before dangerous spreadsheet formula prefixes. Source row numbers refer to input data rows, excluding headers.",
      "Summary fields ending _pct are 0-100 values in R and exported as numeric Excel fractions with 0.0% formatting. Changes ending _pp remain numeric percentage-point differences. Source fields are not rescaled.",
      "Blank analytical cells mean unavailable, failed eligibility or no known denominator. They must not be read as zero or as evidence that no behaviour occurred."), stringsAsFactors = FALSE)
  definitions <- rbind(definitions, extra)
  # Documentation rows use wide merged text blocks so explanatory sentences remain readable.
  row <- 4L
  text(sheet, row, "Reading the results and methods", style = styles$section, height = 24)
  for (i in seq_len(nrow(definitions))) {
    row <- row + 1L
    text(sheet, row, definitions$term[i], 1:3, styles$focus)
    text(sheet, row, definitions$definition[i], 4:12, styles$body, max(32, min(92, 14 * ceiling(nchar(definitions$definition[i]) / 105))))
  }
  row <- row + 3L
  text(sheet, row, "Raw and derived field dictionary", style = styles$section, height = 24)
  dictionary <- data.frame(table = character(), field = character(), type = character(), definition = character(), stringsAsFactors = FALSE)
  named_tables <- results[vapply(results, is.data.frame, logical(1L))]
  for (nm in names(named_tables)) {
    df <- named_tables[[nm]]
    for (field in names(df)) {
      derived_fields <- attr(raw, "derived_columns")
      is_derived <- nm == "raw_data" && if (length(derived_fields)) field %in% derived_fields else startsWith(field, raw_prefix)
      is_source <- nm == "raw_data" && !is_derived
      definition_field <- if (is_derived) substring(field, nchar(raw_prefix) + 1L) else field
      type <- if (inherits(df[[field]], "Date")) "Date" else if (inherits(df[[field]], "POSIXt")) "Timestamp" else if (is.numeric(df[[field]])) "Number" else if (is.logical(df[[field]])) "Logical" else "Text"
      dictionary <- rbind(dictionary, data.frame(table = nm, field = field, type = type,
        definition = sbm_workbook_definition(definition_field, is_source, config), stringsAsFactors = FALSE))
    }
  }
  row <- row + 1L
  for (j in seq_along(c("Table", "Field", "Type", "Definition"))) text(sheet, row, c("Table", "Field", "Type", "Definition")[j], list(1:2, 3:5, 6L, 7:12)[[j]], styles$header, 25)
  if (nrow(dictionary)) {
    dictionary_rows <- row + seq_len(nrow(dictionary))
    # Four column-vector writes and one body style keep the dictionary cheap to
    # regenerate; per-cell write/style calls grew quadratically with field count.
    for (j in seq_len(ncol(dictionary))) openxlsx::writeData(wb, sheet, safe(dictionary)[[j]],
      startRow = min(dictionary_rows), startCol = c(1L, 3L, 6L, 7L)[j], colNames = FALSE, keepNA = FALSE)
    openxlsx::addStyle(wb, sheet, styles$body, rows = dictionary_rows, cols = 1:12, gridExpand = TRUE, stack = FALSE)
    for (r in dictionary_rows) for (cols in list(1:2, 3:5, 7:12)) openxlsx::mergeCells(wb, sheet, cols = cols, rows = r)
    openxlsx::setRowHeights(wb, sheet, dictionary_rows, pmax(36, pmin(96, 14 * ceiling(nchar(dictionary$definition) / 75))))
    row <- max(dictionary_rows)
  }
  row <- row + 3L
  text(sheet, row, "Settings for this run", style = styles$section, height = 24)
  for (nm in names(config)) {
    value <- config[[nm]]
    if (is.data.frame(value)) value <- apply(value, 1L, function(x) paste(x, collapse = " = "))
    else if (is.list(value)) value <- vapply(value, function(x) paste(x, collapse = " | "), character(1L))
    if (!is.null(names(value))) value <- paste(names(value), as.character(value), sep = " = ")
    else value <- as.character(value)
    joined <- paste(value, collapse = "; ")
    row <- row + 1L
    text(sheet, row, nm, 1:3, styles$focus)
    text(sheet, row, joined, 4:12, styles$body, max(27, min(90, 14 * ceiling(nchar(joined) / 105))))
  }
  row <- row + 3L
  row <- table(sheet, row, results$quality, "Run-level data quality", "Recorded-field completeness does not establish how many scheduled checks were missed.")
  row <- table(sheet, row, results$issues, "Row-level data quality issues", "Source rows join to the audit row field on Raw data. Missing and conflicting observations are retained with their issue explanation.")
  openxlsx::freezePane(wb, sheet, firstActiveRow = 4L)
  openxlsx::pageSetup(wb, sheet, orientation = "landscape", paperSize = 9L, fitToWidth = 1L, fitToHeight = 0L)
  path <- file.path(output_dir, "monitoring-report.xlsx")
  openxlsx::saveWorkbook(wb, path, overwrite = TRUE)
  path
}
